name: 'PFvpn-checkin'

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '35 9 * * *'

jobs:
  leetcode-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: 'Install requirements'
        run: pip install -r requirements.txt
      - name: 'Working'
        env:
          USERS: ${{ secrets.USERS }}
          PWDS: ${{ secrets.PWDS }}
        run: python main.py
